### ISSUE TITLE
manifest for jareware/docker-volume-backup not found: manifest unknown

### ISSUE THREAD

**Issue by andreasotto** [jareware/docker-volume-backup#41]
When following your very first example from README or trying to manually pull docker-volume-backup the result is:

```
# docker pull jareware/docker-volume-backup
Using default tag: latest
Error response from daemon: manifest for jareware/docker-volume-backup:latest not found: manifest unknown: manifest unknown
```

**Comment by jan-brinkmann** [comment]
@andreasotto, this is most likely due to the fact that @jareware provides an image for AMD64 architecture only.

However, you can clone the repository, change into it and run `docker build -t jareware/docker-volume-backup .` there.
This works for me on Raspberry Pis witm ARM architecture.

Please let us know whether this works for you or not.

**Comment by kenhon93** [comment]
@andreasotto you may try this `docker pull jareware/docker-volume-backup:2.4.0`
I think @jareware forgot to add `latest` tag to the latest build.

**Comment by jareware** [comment]
Ugh, yes, looks like I did, sorry. 🤦 

Need to update [release instructions](https://github.com/jareware/docker-volume-backup#releasing), it's the only way one remembers to do anything properly... 😇

**Comment by michael-robbins** [comment]
Also I don't believe 2.4.0 has been pushed to docker hub either?

https://hub.docker.com/r/futurice/docker-volume-backup/tags claims 2.3.0 is the last one pushed 9 months ago (and :latest a year ago)

**Comment by jan-brinkmann** [comment]
Version 2.4.0 is here: https://hub.docker.com/r/jareware/docker-volume-backup/tags
